<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <AppxGeneratePriEnabled>false</AppxGeneratePriEnabled>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" />
    <PackageReference Include="Serilog" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\PresentationTimer.App\PresentationTimer.App.csproj" />
  </ItemGroup>

</Project>
